export const CONSTANTS = {
  categoryOptions_Survey: ["DBA", "DSOM", "DEFAULT", "EDUCATION", "IZOT"],
  catalogStatus_options: ["IN ACTIVE", "IN PROCESS", "PUBLISHED"],
  catalogupdate_options: ["NO UPDATE", "AUTOMATIC UPDATE", "PROMPT USER"],
  expressionOptions: ["Option 1", "Option 2"],
  sectionOptions: ["+", "-", "*", "<", ">", "<=", ">="],
  functionOptions: ["CALCVALUE", "Item 1", "Item 2", "Item 3"],
  questionTypes: [
    "TOGGLE",
    "COUNTRIES",
    "YES/NO",
    "DATE",
    "NUMBER",
    "NUMERIC (0-10)",
    "TEXT",
    "PERCENTAGE",
    "WHOLE NUMBER",
    "MULTITEXT",
    "CURRENCY",
    "YES/NO/NOT SURE",
    "FORMULA",
  ],
  countryList: [
    { name: "Afghanistan", code: "AF" },
    { name: "land Islands", code: "AX" },
    { name: "Albania", code: "AL" },
    { name: "Algeria", code: "DZ" },
    { name: "American Samoa", code: "AS" },
    { name: "AndorrA", code: "AD" },
    { name: "Angola", code: "AO" },
    { name: "Anguilla", code: "AI" },
    { name: "Antarctica", code: "AQ" },
    { name: "Antigua and Barbuda", code: "AG" },
    { name: "Argentina", code: "AR" },
    { name: "Armenia", code: "AM" },
    { name: "Aruba", code: "AW" },
    { name: "Australia", code: "AU" },
    { name: "Austria", code: "AT" },
    { name: "Azerbaijan", code: "AZ" },
    { name: "Bahamas", code: "BS" },
    { name: "Bahrain", code: "BH" },
    { name: "Bangladesh", code: "BD" },
    { name: "Barbados", code: "BB" },
    { name: "Belarus", code: "BY" },
    { name: "Belgium", code: "BE" },
    { name: "Belize", code: "BZ" },
    { name: "Benin", code: "BJ" },
    { name: "Bermuda", code: "BM" },
    { name: "Bhutan", code: "BT" },
    { name: "Bolivia", code: "BO" },
    { name: "Bosnia and Herzegovina", code: "BA" },
    { name: "Botswana", code: "BW" },
    { name: "Bouvet Island", code: "BV" },
    { name: "Brazil", code: "BR" },
    { name: "British Indian Ocean Territory", code: "IO" },
    { name: "Brunei Darussalam", code: "BN" },
    { name: "Bulgaria", code: "BG" },
    { name: "Burkina Faso", code: "BF" },
    { name: "Burundi", code: "BI" },
    { name: "Cambodia", code: "KH" },
    { name: "Cameroon", code: "CM" },
    { name: "Canada", code: "CA" },
    { name: "Cape Verde", code: "CV" },
    { name: "Cayman Islands", code: "KY" },
    { name: "Central African Republic", code: "CF" },
    { name: "Chad", code: "TD" },
    { name: "Chile", code: "CL" },
    { name: "China", code: "CN" },
    { name: "Christmas Island", code: "CX" },
    { name: "Cocos (Keeling) Islands", code: "CC" },
    { name: "Colombia", code: "CO" },
    { name: "Comoros", code: "KM" },
    { name: "Congo", code: "CG" },
    { name: "Congo, The Democratic Republic of the", code: "CD" },
    { name: "Cook Islands", code: "CK" },
    { name: "Costa Rica", code: "CR" },
    { name: "Cote D Ivoire", code: "CI" },
    { name: "Croatia", code: "HR" },
    { name: "Cuba", code: "CU" },
    { name: "Cyprus", code: "CY" },
    { name: "Czech Republic", code: "CZ" },
    { name: "Denmark", code: "DK" },
    { name: "Djibouti", code: "DJ" },
    { name: "Dominica", code: "DM" },
    { name: "Dominican Republic", code: "DO" },
    { name: "Ecuador", code: "EC" },
    { name: "Egypt", code: "EG" },
    { name: "El Salvador", code: "SV" },
    { name: "Equatorial Guinea", code: "GQ" },
    { name: "Eritrea", code: "ER" },
    { name: "Estonia", code: "EE" },
    { name: "Ethiopia", code: "ET" },
    { name: "Falkland Islands (Malvinas)", code: "FK" },
    { name: "Faroe Islands", code: "FO" },
    { name: "Fiji", code: "FJ" },
    { name: "Finland", code: "FI" },
    { name: "France", code: "FR" },
    { name: "French Guiana", code: "GF" },
    { name: "French Polynesia", code: "PF" },
    { name: "French Southern Territories", code: "TF" },
    { name: "Gabon", code: "GA" },
    { name: "Gambia", code: "GM" },
    { name: "Georgia", code: "GE" },
    { name: "Germany", code: "DE" },
    { name: "Ghana", code: "GH" },
    { name: "Gibraltar", code: "GI" },
    { name: "Greece", code: "GR" },
    { name: "Greenland", code: "GL" },
    { name: "Grenada", code: "GD" },
    { name: "Guadeloupe", code: "GP" },
    { name: "Guam", code: "GU" },
    { name: "Guatemala", code: "GT" },
    { name: "Guernsey", code: "GG" },
    { name: "Guinea", code: "GN" },
    { name: "Guinea-Bissau", code: "GW" },
    { name: "Guyana", code: "GY" },
    { name: "Haiti", code: "HT" },
    { name: "Heard Island and Mcdonald Islands", code: "HM" },
    { name: "Holy See (Vatican City State)", code: "VA" },
    { name: "Honduras", code: "HN" },
    { name: "Hong Kong", code: "HK" },
    { name: "Hungary", code: "HU" },
    { name: "Iceland", code: "IS" },
    { name: "India", code: "IN" },
    { name: "Indonesia", code: "ID" },
    { name: "Iran, Islamic Republic Of", code: "IR" },
    { name: "Iraq", code: "IQ" },
    { name: "Ireland", code: "IE" },
    { name: "Isle of Man", code: "IM" },
    { name: "Israel", code: "IL" },
    { name: "Italy", code: "IT" },
    { name: "Jamaica", code: "JM" },
    { name: "Japan", code: "JP" },
    { name: "Jersey", code: "JE" },
    { name: "Jordan", code: "JO" },
    { name: "Kazakhstan", code: "KZ" },
    { name: "Kenya", code: "KE" },
    { name: "Kiribati", code: "KI" },
    { name: "Korea, Democratic People S Republic of", code: "KP" },
    { name: "Korea, Republic of", code: "KR" },
    { name: "Kuwait", code: "KW" },
    { name: "Kyrgyzstan", code: "KG" },
    { name: "Lao People S Democratic Republic", code: "LA" },
    { name: "Latvia", code: "LV" },
    { name: "Lebanon", code: "LB" },
    { name: "Lesotho", code: "LS" },
    { name: "Liberia", code: "LR" },
    { name: "Libyan Arab Jamahiriya", code: "LY" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lithuania", code: "LT" },
    { name: "Luxembourg", code: "LU" },
    { name: "Macao", code: "MO" },
    { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
    { name: "Madagascar", code: "MG" },
    { name: "Malawi", code: "MW" },
    { name: "Malaysia", code: "MY" },
    { name: "Maldives", code: "MV" },
    { name: "Mali", code: "ML" },
    { name: "Malta", code: "MT" },
    { name: "Marshall Islands", code: "MH" },
    { name: "Martinique", code: "MQ" },
    { name: "Mauritania", code: "MR" },
    { name: "Mauritius", code: "MU" },
    { name: "Mayotte", code: "YT" },
    { name: "Mexico", code: "MX" },
    { name: "Micronesia, Federated States of", code: "FM" },
    { name: "Moldova, Republic of", code: "MD" },
    { name: "Monaco", code: "MC" },
    { name: "Mongolia", code: "MN" },
    { name: "Montenegro", code: "ME" },
    { name: "Montserrat", code: "MS" },
    { name: "Morocco", code: "MA" },
    { name: "Mozambique", code: "MZ" },
    { name: "Myanmar", code: "MM" },
    { name: "Namibia", code: "NA" },
    { name: "Nauru", code: "NR" },
    { name: "Nepal", code: "NP" },
    { name: "Netherlands", code: "NL" },
    { name: "Netherlands Antilles", code: "AN" },
    { name: "New Caledonia", code: "NC" },
    { name: "New Zealand", code: "NZ" },
    { name: "Nicaragua", code: "NI" },
    { name: "Niger", code: "NE" },
    { name: "Nigeria", code: "NG" },
    { name: "Niue", code: "NU" },
    { name: "Norfolk Island", code: "NF" },
    { name: "Northern Mariana Islands", code: "MP" },
    { name: "Norway", code: "NO" },
    { name: "Oman", code: "OM" },
    { name: "Pakistan", code: "PK" },
    { name: "Palau", code: "PW" },
    { name: "Palestinian Territory, Occupied", code: "PS" },
    { name: "Panama", code: "PA" },
    { name: "Papua New Guinea", code: "PG" },
    { name: "Paraguay", code: "PY" },
    { name: "Peru", code: "PE" },
    { name: "Philippines", code: "PH" },
    { name: "Pitcairn", code: "PN" },
    { name: "Poland", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Puerto Rico", code: "PR" },
    { name: "Qatar", code: "QA" },
    { name: "Reunion", code: "RE" },
    { name: "Romania", code: "RO" },
    { name: "Russian Federation", code: "RU" },
    { name: "RWANDA", code: "RW" },
    { name: "Saint Helena", code: "SH" },
    { name: "Saint Kitts and Nevis", code: "KN" },
    { name: "Saint Lucia", code: "LC" },
    { name: "Saint Pierre and Miquelon", code: "PM" },
    { name: "Saint Vincent and the Grenadines", code: "VC" },
    { name: "Samoa", code: "WS" },
    { name: "San Marino", code: "SM" },
    { name: "Sao Tome and Principe", code: "ST" },
    { name: "Saudi Arabia", code: "SA" },
    { name: "Senegal", code: "SN" },
    { name: "Serbia", code: "RS" },
    { name: "Seychelles", code: "SC" },
    { name: "Sierra Leone", code: "SL" },
    { name: "Singapore", code: "SG" },
    { name: "Slovakia", code: "SK" },
    { name: "Slovenia", code: "SI" },
    { name: "Solomon Islands", code: "SB" },
    { name: "Somalia", code: "SO" },
    { name: "South Africa", code: "ZA" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS" },
    { name: "Spain", code: "ES" },
    { name: "Sri Lanka", code: "LK" },
    { name: "Sudan", code: "SD" },
    { name: "Suriname", code: "SR" },
    { name: "Svalbard and Jan Mayen", code: "SJ" },
    { name: "Swaziland", code: "SZ" },
    { name: "Sweden", code: "SE" },
    { name: "Switzerland", code: "CH" },
    { name: "Syrian Arab Republic", code: "SY" },
    { name: "Taiwan, Province of China", code: "TW" },
    { name: "Tajikistan", code: "TJ" },
    { name: "Tanzania, United Republic of", code: "TZ" },
    { name: "Thailand", code: "TH" },
    { name: "Timor-Leste", code: "TL" },
    { name: "Togo", code: "TG" },
    { name: "Tokelau", code: "TK" },
    { name: "Tonga", code: "TO" },
    { name: "Trinidad and Tobago", code: "TT" },
    { name: "Tunisia", code: "TN" },
    { name: "Turkey", code: "TR" },
    { name: "Turkmenistan", code: "TM" },
    { name: "Turks and Caicos Islands", code: "TC" },
    { name: "Tuvalu", code: "TV" },
    { name: "Uganda", code: "UG" },
    { name: "Ukraine", code: "UA" },
    { name: "United Arab Emirates", code: "AE" },
    { name: "United Kingdom", code: "GB" },
    { name: "United States", code: "US" },
    { name: "United States Minor Outlying Islands", code: "UM" },
    { name: "Uruguay", code: "UY" },
    { name: "Uzbekistan", code: "UZ" },
    { name: "Vanuatu", code: "VU" },
    { name: "Venezuela", code: "VE" },
    { name: "Viet Nam", code: "VN" },
    { name: "Virgin Islands, British", code: "VG" },
    { name: "Virgin Islands, U.S.", code: "VI" },
    { name: "Wallis and Futuna", code: "WF" },
    { name: "Western Sahara", code: "EH" },
    { name: "Yemen", code: "YE" },
    { name: "Zambia", code: "ZM" },
    { name: "Zimbabwe", code: "ZW" },
  ],
  currencyList: [
    { name: "Afghan Afghani", code: "AFN" },
    { name: "Albanian Lek", code: "ALL" },
    { name: "Algerian Dinar", code: "DZD" },
    { name: "Angolan Kwanza", code: "AOA" },
    { name: "Argentine Peso", code: "ARS" },
    { name: "Armenian Dram", code: "AMD" },
    { name: "Aruban Florin", code: "AWG" },
    { name: "Australian Dollar", code: "AUD" },
    { name: "Azerbaijani Manat", code: "AZN" },
    { name: "Bahamian Dollar", code: "BSD" },
    { name: "Bahraini Dinar", code: "BHD" },
    { name: "Bangladeshi Taka", code: "BDT" },
    { name: "Barbadian Dollar", code: "BBD" },
    { name: "Belarusian Ruble", code: "BYN" },
    { name: "Belize Dollar", code: "BZD" },
    { name: "Bermudian Dollar", code: "BMD" },
    { name: "Bhutanese Ngultrum", code: "BTN" },
    { name: "Bitcoin", code: "BTC" },
    { name: "Bolivian Boliviano", code: "BOB" },
    { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM" },
    { name: "Botswanan Pula", code: "BWP" },
    { name: "Brazilian Real", code: "BRL" },
    { name: "Brunei Dollar", code: "BND" },
    { name: "Bulgarian Lev", code: "BGN" },
    { name: "Burundian Franc", code: "BIF" },
    { name: "Cambodian Riel", code: "KHR" },
    { name: "Canadian Dollar", code: "CAD" },
    { name: "Cape Verdean Escudo", code: "CVE" },
    { name: "Cayman Islands Dollar", code: "KYD" },
    { name: "Central African CFA Franc", code: "XAF" },
    { name: "CFP Franc", code: "XPF" },
    { name: "Chilean Peso", code: "CLP" },
    { name: "Chinese Yuan", code: "CNY" },
    { name: "Colombian Peso", code: "COP" },
    { name: "Comorian Franc", code: "KMF" },
    { name: "Congolese Franc", code: "CDF" },
    { name: "Costa Rican Colón", code: "CRC" },
    { name: "Croatian Kuna", code: "HRK" },
    { name: "Cuban Peso", code: "CUP" },
    { name: "Czech Republic Koruna", code: "CZK" },
    { name: "Danish Krone", code: "DKK" },
    { name: "Djiboutian Franc", code: "DJF" },
    { name: "Dominican Peso", code: "DOP" },
    { name: "East Caribbean Dollar", code: "XCD" },
    { name: "Egyptian Pound", code: "EGP" },
    { name: "Eritrean Nakfa", code: "ERN" },
    { name: "Estonian Kroon", code: "EEK" },
    { name: "Ethiopian Birr", code: "ETB" },
    { name: "Euro", code: "EUR" },
    { name: "Falkland Islands Pound", code: "FKP" },
    { name: "Fijian Dollar", code: "FJD" },
    { name: "Gambian Dalasi", code: "GMD" },
    { name: "Georgian Lari", code: "GEL" },
    { name: "Ghanaian Cedi", code: "GHS" },
    { name: "Gibraltar Pound", code: "GIP" },
    { name: "Gold Ounce", code: "XAU" },
    { name: "Guatemalan Quetzal", code: "GTQ" },
    { name: "Guernsey Pound", code: "GGP" },
    { name: "Guinean Franc", code: "GNF" },
    { name: "Guyanaese Dollar", code: "GYD" },
    { name: "Haitian Gourde", code: "HTG" },
    { name: "Honduran Lempira", code: "HNL" },
    { name: "Hong Kong Dollar", code: "HKD" },
    { name: "Hungarian Forint", code: "HUF" },
    { name: "Icelandic Króna", code: "ISK" },
    { name: "Indian Rupee", code: "INR" },
    { name: "Indonesian Rupiah", code: "IDR" },
    { name: "Iranian Rial", code: "IRR" },
    { name: "Iraqi Dinar", code: "IQD" },
    { name: "Israeli New Sheqel", code: "ILS" },
    { name: "Jamaican Dollar", code: "JMD" },
    { name: "Japanese Yen", code: "JPY" },
    { name: "Jersey Pound", code: "JEP" },
    { name: "Jordanian Dinar", code: "JOD" },
    { name: "Kazakhstani Tenge", code: "KZT" },
    { name: "Kenyan Shilling", code: "KES" },
    { name: "Kuwaiti Dinar", code: "KWD" },
    { name: "Kyrgystani Som", code: "KGS" },
    { name: "Laotian Kip", code: "LAK" },
    { name: "Latvian Lats", code: "LVL" },
    { name: "Lebanese Pound", code: "LBP" },
    { name: "Lesotho Loti", code: "LSL" },
    { name: "Liberian Dollar", code: "LRD" },
    { name: "Libyan Dinar", code: "LYD" },
    { name: "Lithuanian Litas", code: "LTL" },
    { name: "Macanese Pataca", code: "MOP" },
    { name: "Macedonian Denar", code: "MKD" },
    { name: "Malagasy Ariary", code: "MGA" },
    { name: "Malawian Kwacha", code: "MWK" },
    { name: "Malaysian Ringgit", code: "MYR" },
    { name: "Maldivian Rufiyaa", code: "MVR" },
    { name: "Mauritanian Ouguiya", code: "MRO" },
    { name: "Mauritian Rupee", code: "MUR" },
    { name: "Mexican Peso", code: "MXN" },
    { name: "Moldovan Leu", code: "MDL" },
    { name: "Mongolian Tugrik", code: "MNT" },
    { name: "Moroccan Dirham", code: "MAD" },
    { name: "Mozambican Metical", code: "MZN" },
    { name: "Myanma Kyat", code: "MMK" },
    { name: "Namibian Dollar", code: "NAD" },
    { name: "Nepalese Rupee", code: "NPR" },
    { name: "Netherlands Antillean Guilder", code: "ANG" },
    { name: "New Taiwan Dollar", code: "TWD" },
    { name: "New Zealand Dollar", code: "NZD" },
    { name: "Nicaraguan Córdoba", code: "NIO" },
    { name: "Nigerian Naira", code: "NGN" },
    { name: "North Korean Won", code: "KPW" },
    { name: "Norwegian Krone", code: "NOK" },
    { name: "Omani Rial", code: "OMR" },
    { name: "Pakistani Rupee", code: "PKR" },
    { name: "Palladium Ounce", code: "XPD" },
    { name: "Panamanian Balboa", code: "PAB" },
    { name: "Papua New Guinean Kina", code: "PGK" },
    { name: "Paraguayan Guarani", code: "PYG" },
    { name: "Peruvian Nuevo Sol", code: "PEN" },
    { name: "Philippine Peso", code: "PHP" },
    { name: "Platinum Ounce", code: "XPT" },
    { name: "Polish Zloty", code: "PLN" },
    { name: "Qatari Rial", code: "QAR" },
    { name: "Romanian Leu", code: "RON" },
    { name: "Russian Ruble", code: "RUB" },
    { name: "Rwandan Franc", code: "RWF" },
    { name: "Saint Helena Pound", code: "SHP" },
    { name: "Salvadoran Colón", code: "SVC" },
    { name: "Samoan Tala", code: "WST" },
    { name: "Sao Tome and Principe Dobra", code: "STD" },
    { name: "Saudi Riyal", code: "SAR" },
    { name: "Serbian Dinar", code: "RSD" },
    { name: "Seychellois Rupee", code: "SCR" },
    { name: "Sierra Leonean Leone", code: "SLL" },
    { name: "Silver Ounce", code: "XAG" },
    { name: "Singapore Dollar", code: "SGD" },
    { name: "Solomon Islands Dollar", code: "SBD" },
    { name: "Somali Shilling", code: "SOS" },
    { name: "South African Rand", code: "ZAR" },
    { name: "South Korean Won", code: "KRW" },
    { name: "Special Drawing Rights", code: "XDR" },
    { name: "Sri Lankan Rupee", code: "LKR" },
    { name: "Sudanese Pound", code: "SDG" },
    { name: "Surinamese Dollar", code: "SRD" },
    { name: "Swazi Lilangeni", code: "SZL" },
    { name: "Swedish Krona", code: "SEK" },
    { name: "Swiss Franc", code: "CHF" },
    { name: "Syrian Pound", code: "SYP" },
    { name: "Tajikistani Somoni", code: "TJS" },
    { name: "Tanzanian Shilling", code: "TZS" },
    { name: "Thai Baht", code: "THB" },
    { name: "Tongan Pa'anga", code: "TOP" },
    { name: "Trinidad and Tobago Dollar", code: "TTD" },
    { name: "Tunisian Dinar", code: "TND" },
    { name: "Turkish Lira", code: "TRY" },
    { name: "Turkmenistani Manat", code: "TMT" },
    { name: "Ugandan Shilling", code: "UGX" },
    { name: "Ukrainian Hryvnia", code: "UAH" },
    { name: "United Arab Emirates Dirham", code: "AED" },
    { name: "Uruguayan Peso", code: "UYU" },
    { name: "Uzbekistan Som", code: "UZS" },
    { name: "Vanuatu Vatu", code: "VUV" },
    { name: "Venezuelan Bolívar", code: "VEF" },
    { name: "Vietnamese Dong", code: "VND" },
    { name: "Yemeni Rial", code: "YER" },
    { name: "Zambian Kwacha", code: "ZMW" },
    { name: "Zimbabwean Dollar", code: "ZWL" },
  ],
  optioncurrency: [
    "Afghanistan - Afghani (AFN)",
    "Albania - Lek (ALL)",
    "Algeria - Algerian Dinar (DZD)",
    "American Samoa - US Dollar (USD)",
    "Andorra - Euro (EUR)",
    "Angola - Kwanza (AOA)",
    "Anguilla - East Caribbean Dollar (XCD)",
    "Antigua and Barbuda - East Caribbean Dollar (XCD)",
    "Argentina - Argentine Peso (ARS)",
    "Armenia - Armeniam Dram (AMD)",
    "Aruba - Aruban Florin (AWG)",
    "Australia - Australian Dollar (AUD)",
    "Austria - Euro (EUR)",
    "Azerbaijan - Azerbaijanian Manat (AZN)",
    "Bahamas - Bahamian Dollar (BSD)",
    "Bahrain - Bahraini Dinar (BHD)",
    "Bangladesh - Taka (BDT)",
    "Barbados - Barbados Dollar (BBD)",
    "Belarus - Belarusian Ruble (BYN)",
    "Belgium - Euro (EUR)",
    "Belize - Belize Dollar (BZD)",
    "Benin - CFA Franc (BCEAO) (XOF)",
    "Bermuda - Bermudian Dollar (BMD)",
    "Bhutan - Ngultrum (BTN)",
    "Bolivia (Plurinat.State) - Boliviano (BOB)",
    "Bonaire/S.Eustatius/Saba - US Dollar (USD)",
    "Bosnia and Herzegovina - Convertible Mark (BAM)",
    "Botswana - Pula (BWP)",
    "Brazil - Brazilian Real (BRL)",
    "British Indian Ocean Ter - US Dollar (USD)",
    "British Virgin Islands - US Dollar (USD)",
    "Brunei Darussalam - Brunei Dollar (BND)",
    "Bulgaria - Bulgarian Lev (BGN)",
    "Burkina Faso - CFA Franc (BCEAO) (XOF)",
    "Burundi - Burundi Franc (BIF)",
    "Cabo Verde - Cabo Verde Escudo (CVE)",
    "Cambodia - Riel (KHR)",
    "Cameroon - CFA Franc (BEAC) (XAF)",
    "Canada - Canadian Dollar (CAD)",
    "Cayman Islands - Cayman Islands Dollar (KYD)",
    "Central African Republic - CFA Franc (BEAC) (XAF)",
    "Chad - CFA Franc (BEAC) (XAF)",
    "Channel Islands - Pound Sterling (GBP)",
    "Chile - Chilean Peso (CLP)",
    "China - Yuan Renminbi (CNY)",
    "China, Hong Kong SAR - Hong Kong Dollar (HKD)",
    "China, Macao SAR - Pataca (MOP)",
    "Taiwan Province of China - New Taiwan Dollar (TWD)",
    "Christmas Island - Australian Dollar (AUD)",
    "Cocos (Keeling) Islands - Australian Dollar (AUD)",
    "Colombia - Colombian Peso (COP)",
    "Coordinating Working Party on Fishery Statistics (CWP)",
    "Comoros - Comoro Franc (KMF)",
    "Congo - CFA Franc (BEAC) (XAF)",
    "Congo, Dem. Rep. of the - Congolese Franc (CDF)",
    "Cook Islands - New Zealand Dollar (NZD)",
    "Costa Rica - Costa Rican Colón (CRC)",
    "Côte d'Ivoire - CFA Franc (BCEAO) (XOF)",
    "Croatia - Croatian Kuna (HRK)",
    "Cuba - Cuban Peso (CUP)",
    "Curaçao - Netherlands Antillian Guilder (ANG)",
    "Cyprus - Euro (EUR)",
    "Czechia - Czech Koruna (CZK)",
    "Denmark - Danish Krone (DKK)",
    "Djibouti - Djibouti Franc (DJF)",
    "Dominica - East Caribbean Dollar (XCD)",
    "Dominican Republic - Dominican Peso (DOP)",
    "Ecuador - US Dollar (USD)",
    "Egypt - Egyptian Pound (EGP)",
    "El Salvador - US Dollar (USD)",
    "Equatorial Guinea - CFA Franc (BEAC) (XAF)",
    "Eritrea - Nakfa (ERN)",
    "Estonia - Euro (EUR)",
    "Ethiopia - Ethiopian Birr (ETB)",
    "Falkland Is.(Malvinas) - Falkland Islands Pound (FKP)",
    "Faroe Islands - Danish Krone (DKK)",
    "Fiji, Republic of - Fiji Dollar (FJD)",
    "Finland - Euro (EUR)",
    "France - Euro (EUR)",
    "French Guiana - Euro (EUR)",
    "French Polynesia - CFP Franc (XPF)",
    "French Southern Terr - Euro (EUR)",
    "Gabon - CFA Franc (BEAC) (XAF)",
    "Gambia - Dalasi (GMD)",
    "Georgia - Lari (GEL)",
    "Germany - Euro (EUR)",
    "Ghana - Ghana Cedi (GHS)",
    "Gibraltar - Gibraltar Pound (GIP)",
    "Greece - Euro (EUR)",
    "Greenland - Danish Krone (DKK)",
    "Grenada - East Caribbean Dollar (XCD)",
    "Guadeloupe - Euro (EUR)",
    "Guam - US Dollar (USD)",
    "Guatemala - Quetzal (GTQ)",
    "Guernsey - Pound Sterling (GBP)",
    "Guinea - Guinea Franc (GNF)",
    "Guinea-Bissau - CFA Franc (BCEAO) (XOF)",
    "Guyana - Guyana Dollar (GYD)",
    "Haiti - Gourde (HTG)",
    "Honduras - Lempira (HNL)",
    "Hungary - Forint (HUF)",
    "Iceland - Iceland Króna (ISK)",
    "India - Indian Rupee (INR)",
    "Indonesia - Rupiah (IDR)",
    "Iran (Islamic Rep. of) - Iranian Rial (IRR)",
    "Iraq - Iraqi Dinar (IQD)",
    "Ireland - Euro (EUR)",
    "Isle of Man - Pound Sterling (GBP)",
    "Israel - New Israeli Sheqel (ILS)",
    "Italy - Euro (EUR)",
    "Jamaica - Jamaican Dollar (JMD)",
    "Japan - Yen (JPY)",
    "Jersey - Pound Sterling (GBP)",
    "Jordan - Jordanian Dinar (JOD)",
    "Kazakhstan - Tenge (KZT)",
    "Kenya - Kenyan Shilling (KES)",
    "Kiribati - Australian Dollar (AUD)",
    "Korea, Dem. People's Rep - North Korean Won (KPW)",
    "Korea, Republic of - Won (KRW)",
    "Kuwait - Kuwaiti Dinar (KWD)",
    "Kyrgyzstan - Som (KGS)",
    "Lao People's Dem. Rep. - Kip (LAK)",
    "Latvia - Euro (EUR)",
    "Lebanon - Lebanese Pound (LBP)",
    "Lesotho - Loti (LSL)",
    "Liberia - Liberian Dollar (LRD)",
    "Libya - Libyan Dinar (LYD)",
    "Liechtenstein - Swiss Franc (CHF)",
    "Lithuania - Euro (EUR)",
    "Luxembourg - Euro (EUR)",
    "Macedonia, Fmr Yug Rp of - Denar (MKD)",
    "Madagascar - Malagasy Ariary (MGA)",
    "Malawi - Malawi Kwacha (MWK)",
    "Malaysia - Malaysian Ringgit (MYR)",
    "Maldives - Rufiyaa (MVR)",
    "Mali - CFA Franc (BCEAO) (XOF)",
    "Malta - Euro (EUR)",
    "Marshall Islands - US Dollar (USD)",
    "Martinique - Euro (EUR)",
    "Mauritania - Ouguiya (MRO)",
    "Mauritius - Mauritius Rupee (MUR)",
    "Mayotte - Euro (EUR)",
    "Mexico - Mexican Peso (MXN)",
    "Micronesia,Fed.States of - US Dollar (USD)",
    "Moldova, Republic of - Moldovan Leu (MDL)",
    "Mongolia - Tugrik (MNT)",
    "Montenegro - Euro (EUR)",
    "Montserrat - East Caribbean Dollar (XCD)",
    "Morocco - Moroccan Dirham (MAD)",
    "Mozambique - Metical (MZN)",
    "Myanmar - Kyat (MMK)",
    "Namibia - Namibian Dollar (NAD)",
    "Nauru - Australian Dollar (AUD)",
    "Nepal - Nepalese Rupee (NPR)",
    "Netherlands - Euro (EUR)",
    "New Caledonia - CFP Franc (XPF)",
    "New Zealand - New Zealand Dollar (NZD)",
    "Nicaragua - Córdoba Oro (NIO)",
    "Niger - CFA Franc (BCEAO) (XOF)",
    "Nigeria - Naira (NGN)",
    "Niue - New Zealand Dollar (NZD)",
    "Northern Mariana Is. - US Dollar (USD)",
    "Norway - Norwegian Krone (NOK)",
    "Oman - Rial Omani (OMR)",
    "Pakistan - Pakistan Rupee (PKR)",
    "Palau - US Dollar (USD)",
    "Panama - Balboa (PAB)",
    "Papua New Guinea - Kina (PGK)",
    "Paraguay - Guaraní (PYG)",
    "Peru - Sol (PEN)",
    "Philippines - Philippine Peso (PHP)",
    "Pitcairn Islands - New Zealand Dollar (NZD)",
    "Poland - Zloty (PLN)",
    "Portugal - Euro (EUR)",
    "Puerto Rico - US Dollar (USD)",
    "Qatar - Qatari Rial (QAR)",
    "Réunion - Euro (EUR)",
    "Romania - Romanian Leu (RON)",
    "Russian Federation - Russian Ruble (RUB)",
    "Rwanda - Rwanda Franc (RWF)",
    "Saint Barthélemy - Euro (EUR)",
    "Saint Helena - Saint Helena Pound (SHP)",
    "Saint Kitts and Nevis - East Caribbean Dollar (XCD)",
    "Saint Lucia - East Caribbean Dollar (XCD)",
    "Saint-Martin - Euro (EUR)",
    "St. Pierre and Miquelon - Euro (EUR)",
    "Saint Vincent/Grenadines - East Caribbean Dollar (XCD)",
    "Samoa - Tala (WST)",
    "Sao Tome and Principe - Dobra (STD)",
    "Saudi Arabia - Saudi Riyal (SAR)",
    "Senegal - CFA Franc (BCEAO) (XOF)",
    "Serbia - Serbian Dinar (RSD)",
    "Seychelles - Seychelles Rupee (SCR)",
    "Sierra Leone - Leone (SLL)",
    "Singapore - Singapore Dollar (SGD)",
    "Sint Maarten - Netherlands Antillian Guilder (ANG)",
    "Slovakia - Euro (EUR)",
    "Slovenia - Euro (EUR)",
    "Solomon Islands - Solomon Islands Dollar (SBD)",
    "Somalia - Somali Shilling (SOS)",
    "South Africa - Rand (ZAR)",
    "South Sudan - South Sudanese Pound (SSP)",
    "Spain - Euro (EUR)",
    "Sri Lanka - Sri Lanka Rupee (LKR)",
    "Sudan - Sudanese Pound (SDG)",
    "Suriname - Suriname Dollar (SRD)",
    "Swaziland - Lilangeni (SZL)",
    "Sweden - Swedish Krona (SEK)",
    "Switzerland - Swiss Franc (CHF)",
    "Syrian Arab Republic - Syrian Pound (SYP)",
    "Tajikistan - Somoni (TJS)",
    "Tanzania, United Rep. of - Tanzanian Shilling (TZS)",
    "Thailand - Baht (THB)",
    "Timor-Leste - US Dollar (USD)",
    "Togo - CFA Franc (BCEAO) (XOF)",
    "Tokelau - New Zealand Dollar (NZD)",
    "Tonga - Pa'anga (TOP)",
    "Trinidad and Tobago - Trinidad and Tobago Dollar (TTD)",
    "Tunisia - Tunisian Dinar (TND)",
    "Turkey - Turkish Lira (TRY)",
    "Turkmenistan - Turkmenistan New Manat",
    "Country name Currency name Currency ISO code",
    "Uganda Uganda Shilling UGX",
    "Ukraine Hryvnia UAH",
    "United Arab Emirates UAE Dirham AED",
    "United Kingdom Pound Sterling GBP",
    "United States of America US Dollar USD",
    "US Virgin Islands US Dollar USD",
    "Uruguay Peso Uruguayo UYU",
    "Uzbekistan Uzbekistan Sum UZS",
    "Vanuatu Vatu VUV",
    "Venezuela, Boliv Rep of Bolívar VEF",
    "VietNam Dong VND",
    "Wallis and Futuna Is. CFP Franc XPF",
    "Western Sahara Moroccan Dirham MAD",
    "Yemen Yemeni Rial YER",
    "Zambia Zambian Kwacha ZMW",
    "Zimbabwe Zimbabwe Dollar ZWL",
  ],
  yesno: ["YES", "NO"],
  number: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
  yesNoNotSure: ["YES", "NO", "NOT SURE"],
  languagesOptions: [
    "Afrikaans",
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian",
    "Assamese",
    "Azerbaijani",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Cambodian (Khmer)",
    "Catalan",
    "Cebuano",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chinese (Mandarin)",
    "Chinese (Mandarin, Cantonese, etc.)",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dutch",
    "Dzongkha (Bhutanese)",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Filipino",
    "Filipino (Tagalog)",
    "Finnish",
    "French",
    "Frisian",
    "Fulah",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Greenlandic",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hawaiian",
    "Hebrew",
    "Hindi",
    "Hmong",
    "Hungarian",
    "Icelandic",
    "Igbo",
    "Indonesian",
    "Interlingua",
    "Interlingue (Occidental)",
    "Inuktitut",
    "Inupiaq",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kalaallisut (Greenlandic)",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Khmer (Cambodian)",
    "Kikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Kirundi",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kwanyama",
    "Kyrgyz",
    "Lao",
    "Latin",
    "Latvian",
    "Limburgish",
    "Lingala",
    "Lithuanian",
    "Lojban",
    "Lombard",
    "Luganda",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Manx",
    "Maori",
    "Marathi",
    "Marshallese",
    "Moldovan",
    "Mongolian",
    "Montenegrin",
    "Nauruan",
    "Navajo",
    "Ndonga",
    "Nepali",
    "North Ndebele",
    "Northern Sami",
    "Norwegian",
    "Norwegian Bokmål",
    "Norwegian Nynorsk",
    "Occitan",
    "Ojibwe",
    "Old Church Slavonic",
    "Oriya",
    "Oromo",
    "Ossetian",
    "Pali",
    "Papiamento",
    "Pashto",
    "Persian (Farsi)",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Rhaeto-Romance",
    "Romanian",
    "Russian",
    "Rwandan",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Sardinian",
    "Scots Gaelic",
    "Scottish Gaelic",
    "Serbian",
    "Serbo-Croatian",
    "Sesotho",
    "Setswana",
    "Shona",
    "Sichuan Yi",
    "Sindhi",
    "Sinhalese",
    "Slovak",
    "Slovenian",
    "Somali",
    "South Ndebele",
    "Southern Sotho",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tonga",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Twi",
    "Uighur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Walloon",
    "Welsh",
    "Western Frisian",
    "Wolof",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang",
    "Zulu",
  ],
  timeZoneOptions: [
    "AFRICA/ABIDJAN(FEBRUARY 16TH,6:40AM)",
    "AFRICA/ACCRA(FEBRUARY 16TH,6:40AM)",
    "AFRICA/ADDIS_ABABA(FEBRUARY 16TH,9:40AM)",
    "AFRICA/ALGIERS(FEBRUARY 16TH,7:40AM)",
    "AFRICA/ASMARA(FEBRUARY 16TH,9:40AM)",
    " AFRICA/ASMERA(FEBRUARY 16TH,9:40AM)",
    "AFRICA/BANGUI(FEBRUARY 16TH,7:40AM)",
    "AFRICA/BAMAKO(FEBRUARY 16TH,6:40AM)",
  ],
};
