import PasswordSucess from "../pages/SetPassword/PasswordSuccess";

export const ROUTES_CONSTANTS = {
  LOGIN: "/",
  NEWLOGIN:'/newlogin',
  NEWREGISTER:'/newregister',
  AUTH: "/auth",
  LOGOUT: "/logout",
  REGISTER: "/register",
  HOME: "/home",
  ACCOUNT: "/accounts",
  ACCOUNT_PARAM: "/accounts/:accountIds",
  ACCESS: "/access",
  MYPROFILE: "/myprofile",
  OPPORTUNITIES: "/opportunities",
  OPPORTUNITIES_DATA: "opportunitiesdata",
  QUOTES: "/quotes",
  QUOTES_CREATION: "/quotecreation",
  GUIDED_SELLING_NEW: "/guidedselling_new",
  DEMAND: "/demand",
  FORECAST: "/forecast",
  ROLE_SETUP: "/catalog-roles",
  COMPANY_PROFILE: "/admin-company-profile",
  COMPANY_ORGS: "/companyorgs",
  ALERT: "/admin-alerts",
  CONTENT: "/catalog-contents",
  DOC_TYPES: "/doctypes",
  TEMPLATES: "/template-quotes",
  SETUP: "/setup",
  SETUP_NEW: "/setupnew",
  SETUP_NEW_PARAM: "/setupnew/:id",
  WHEREUSED: "/whereused",
  PEOPLE: "/people-admin-list",
  CONFIG: "/config",
  LOOKUPS: "/lookups",
  SECURITY: "/security",
  ITEMS: "/items",
  // REG_SUCCESS: "/regsuccess",
  SETPASSWORD: "setpassword",
  PROMPT_USER: "/prompuser",
  otpVarification: "/OtpVerification",
  FORGOTPASSWORD: "/forgotPassword",
  LOGACCOUNT: "/logaccount",
  RESETPASSWORD: "/resetPassword",
  STRIPE: "/payment-gateway",
  PASSWORDSUCCESS: "/passwordsuccess",
  MAINTENANCE: "/maintenance"
};
